-- MySQL Script generated by MySQL Workbench
-- Fri Nov  6 17:02:04 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `name` VARCHAR(20) NOT NULL,
  `email` VARCHAR(45) NULL,
  `phone_number` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `u_id` VARCHAR(45) NULL,
  PRIMARY KEY (`name`),
  UNIQUE INDEX `u_id_UNIQUE` (`u_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`calendar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`calendar` (
  `cal_id` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`cal_id`),
  CONSTRAINT `u_id`
    FOREIGN KEY (`cal_id`)
    REFERENCES `mydb`.`user` (`u_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`category` (
  `title` VARCHAR(20) NOT NULL,
  `color` VARCHAR(45) NULL,
  `ctg_id` VARCHAR(45) NULL,
  `cal_id` VARCHAR(45) NULL,
  PRIMARY KEY (`title`),
  UNIQUE INDEX `ctg_id_UNIQUE` (`ctg_id` ASC) VISIBLE,
  UNIQUE INDEX `cal_id_UNIQUE` (`cal_id` ASC) VISIBLE,
  CONSTRAINT `cal_id`
    FOREIGN KEY (`cal_id`)
    REFERENCES `mydb`.`calendar` (`cal_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`checklist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`checklist` (
  `title` VARCHAR(20) NOT NULL,
  `u_id` VARCHAR(45) NULL,
  `ctg_id` VARCHAR(45) NULL,
  `chk_id` VARCHAR(45) NULL,
  PRIMARY KEY (`title`),
  UNIQUE INDEX `u_id_UNIQUE` (`u_id` ASC) VISIBLE,
  UNIQUE INDEX `ctg_id_UNIQUE` (`ctg_id` ASC) VISIBLE,
  UNIQUE INDEX `chk_id_UNIQUE` (`chk_id` ASC) VISIBLE,
  CONSTRAINT `u_id`
    FOREIGN KEY (`u_id`)
    REFERENCES `mydb`.`user` (`u_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ctg_id`
    FOREIGN KEY (`ctg_id`)
    REFERENCES `mydb`.`category` (`ctg_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`event` (
  `title` VARCHAR(20) NOT NULL,
  `at_time` VARCHAR(45) NULL,
  `date` VARCHAR(45) NULL,
  `duration` VARCHAR(45) NULL,
  `evt_id` VARCHAR(45) NULL,
  `ctg_id` VARCHAR(45) NULL,
  `ent_id` VARCHAR(45) NULL,
  PRIMARY KEY (`title`),
  UNIQUE INDEX `evt_id_UNIQUE` (`evt_id` ASC) VISIBLE,
  UNIQUE INDEX `ctg_id_UNIQUE` (`ctg_id` ASC) VISIBLE,
  UNIQUE INDEX `ent_id_UNIQUE` (`ent_id` ASC) VISIBLE,
  CONSTRAINT `ctg_id`
    FOREIGN KEY (`ctg_id`)
    REFERENCES `mydb`.`category` (`ctg_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ent_id`
    FOREIGN KEY (`ent_id`)
    REFERENCES `mydb`.`entry` (`ent_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`entry`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`entry` (
  `title` VARCHAR(20) NOT NULL,
  `ent_id` VARCHAR(45) NULL,
  `chk_id` VARCHAR(45) NULL,
  `evt_id` VARCHAR(45) NULL,
  PRIMARY KEY (`title`),
  UNIQUE INDEX `ent_id_UNIQUE` (`ent_id` ASC) VISIBLE,
  UNIQUE INDEX `chk_id_UNIQUE` (`chk_id` ASC) VISIBLE,
  UNIQUE INDEX `evt_id_UNIQUE` (`evt_id` ASC) VISIBLE,
  CONSTRAINT `chk_id`
    FOREIGN KEY (`chk_id`)
    REFERENCES `mydb`.`checklist` (`chk_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `evt_id`
    FOREIGN KEY (`evt_id`)
    REFERENCES `mydb`.`event` (`evt_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
